#!/bin/bash
#By Alireza
username=$1
password=$2

if echo "$username" | grep -qE '^[a-zA-Z0-9]+$'; then
   sudo adduser $username --shell /usr/sbin/nologin &
   wait
fi
if echo "$password" | grep -qE '^[-a-zA-Z0-9-@]+$'; then
  sudo passwd $username <<!
  $password
  $password
  !
fi


