#!/bin/bash
#By Alireza


if [[ "$1" =~ [^a-zA-Z0-9-] ]]; then
echo "Invalid"
else
sudo adduser $1 --shell /usr/sbin/nologin &
wait
fi
if [[ "$2" =~ [^a-zA-Z0-9-@] ]]; then
echo "Invalid"
else
sudo passwd $1 <<!
$2
$2
!
fi
